import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/Theme-provider";
import { ModeToggle } from "@/components/ModeToggle";
{
  /* 
  import { ClerkProvider } from "@clerk/nextjs";
  import { dark } from "@clerk/themes";
  */
}
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Digital Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* <ClerkProvider
          appearance={{
            baseTheme: dark,
          }}
        >*/}
        <>
        <main className=" w-full overflow-x-hidden">
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
           
            {children}
          </ThemeProvider>
        </main>
        </>
        {/*   </ClerkProvider>*/}
      </body>
    </html>
  );
}
