import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/Theme-provider";
import { ModeToggle } from "@/components/ModeToggle";
import SideBar from "./components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Digital Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section>
          <main className=" w-full overflow-x-hidden mx-auto">
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <div>
        

                <div className=" flex w-full   dark:bg-black bg-white relative min-h-screen">
                  <div className=" absolute top-0 left-0 right-0 ">
                    <div className=" bg-indigo-500/85 min-w-[150px] blur-[250px] max-w-[350px] h-[200px]"></div>
                  </div>
                  <div className="md:p-3">
                    <SideBar />
                  </div>
                  {children}
                </div>
              </div>
            </ThemeProvider>
          </main>
        </section>
      </body>
    </html>
  );
}
