import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/Theme-provider";
import { ModeToggle } from "@/components/ModeToggle";
import SideBar from "./components/SideBar";
import TopBar from "./components/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Your Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <main className=" w-full overflow-x-hidden">
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div className=" fixed z-50  right-0 bottom-0 m-6 p-3">
              <ModeToggle />
            </div>
            <TopBar />
            <div className=" flex flex-row">
              <SideBar />
              {children}
            </div>
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
